// Generated by gencpp from file beginner_tutorials/StringFlip.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_STRINGFLIP_H
#define BEGINNER_TUTORIALS_MESSAGE_STRINGFLIP_H

#include <ros/service_traits.h>


#include <beginner_tutorials/StringFlipRequest.h>
#include <beginner_tutorials/StringFlipResponse.h>


namespace beginner_tutorials
{

struct StringFlip
{

typedef StringFlipRequest Request;
typedef StringFlipResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StringFlip
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::StringFlip > {
  static const char* value()
  {
    return "c63e85f503b805d84df783e71c6bb0d2";
  }

  static const char* value(const ::beginner_tutorials::StringFlip&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::StringFlip > {
  static const char* value()
  {
    return "beginner_tutorials/StringFlip";
  }

  static const char* value(const ::beginner_tutorials::StringFlip&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::StringFlipRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::StringFlip > 
template<>
struct MD5Sum< ::beginner_tutorials::StringFlipRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::StringFlip >::value();
  }
  static const char* value(const ::beginner_tutorials::StringFlipRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::StringFlipRequest> should match 
// service_traits::DataType< ::beginner_tutorials::StringFlip > 
template<>
struct DataType< ::beginner_tutorials::StringFlipRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::StringFlip >::value();
  }
  static const char* value(const ::beginner_tutorials::StringFlipRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::StringFlipResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::StringFlip > 
template<>
struct MD5Sum< ::beginner_tutorials::StringFlipResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::StringFlip >::value();
  }
  static const char* value(const ::beginner_tutorials::StringFlipResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::StringFlipResponse> should match 
// service_traits::DataType< ::beginner_tutorials::StringFlip > 
template<>
struct DataType< ::beginner_tutorials::StringFlipResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::StringFlip >::value();
  }
  static const char* value(const ::beginner_tutorials::StringFlipResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_STRINGFLIP_H
